Service : auth


Releases:
  -
    Version: 1.0.0
    Path: ./swagger1_0_0.yaml
    tag: InternalRelease
  -
    Version: 0.0.1
    Path: ./swagger0_0_1.yaml
    tag: Production
  -
    Version: 0.0.2
    Path: ./swagger0_0_2.yaml
    tag: development

